### ISSUE TITLE
gradethis cannot inspect s3 methods and ...

### ISSUE THREAD

**Issue by chendaniely** [rstudio-education/gradethis#83] opened 2019-10-10 20:45 UTC
for example `mean` only knows of `x, ...` `mean.default` knows of `x`, `trim`, `na.rm`

```
a <- quote(mean(1:10, trim = 1, na.rm = TRUE))
b <- quote(mean(1:10, 1, TRUE))
```

are "execution equivalent" but "code mismatch"

```
grade_code(grader_args = list(user_quo = b, solution_quo = a))
```
returns 

```
$message
I did not expect your call to mean() to include 1. You may have included an unnecessary argument, or you may have left out or misspelled an important argument name.  Try it again. Perseverence is the key to success.

$correct
[1] FALSE

attr(,"class")
[1] "grader_graded"
```

**Comment by chendaniely** [comment] 2019-10-10 20:49
`...` arguments should almost be named arguments. Can make another stricter mode that will error if user/instructor passes in an unnamed argument

**Comment by gadenbuie** [comment] 2021-01-06 18:58
Duplicate of #75

**Closed by gadenbuie** 2021-01-06 18:58 UTC
