### ISSUE TITLE
Copy to clipboard generates exercise.checker error if pasted as solution

### ISSUE THREAD

**Issue by JamesSul** [rstudio-education/gradethis#142] opened 2020-08-27 18:19 UTC
This doesn't happen on every problem, but when you are using Windows 10 and select the copy-to-clipboard button, you receive an "Error occurred while evaluating 'exercise.checker'
You can replicate this error by using the provided lego-sales tutorial at [https://gallery.shinyapps.io/lego-sales/#section-discretizing-variables](https://gallery.shinyapps.io/lego-sales/#section-discretizing-variables) and for the "Grouping by age" question...

* Make sure you are using Windows 10
* select Hints->Next Hint until you get to the final hint that provides the solution
* select the Copy to Clipboard button
* paste the code into the code box
* select the Submit Answer button

The code will actually run fine but Submit Answer will generate the error:
`Error occured while evaluating 'exercise.checker'.`

Highlight copying ctrl-c works properly and doesn't generate an error so I suspect this is related to the way copy to clipboard behaves on Windows 10.

**Comment by gadenbuie** [comment] 2021-01-06 22:21
Possible duplicate of #135

**Comment by gadenbuie** [comment] 2021-01-08 17:58
Thank you for the report! I've moved this issue to https://github.com/rstudio/learnr/issues/466

**Closed by gadenbuie** 2021-01-08 17:58 UTC
